name: Linters piplene
on: [ push ]
defaults:
  run:
    shell: bash
jobs:
  Linters:
    name: Linters check code requrements
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run linter check script
        run: |
          pip install cpplint
          ./tools/linter-checks.sh
