name: Testing piplene
on: [ push ]
defaults:
  run:
    shell: bash
jobs:
  Consistent:
    name: Run library tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build tests
        run: |
          sudo apt update
          sudo apt install valgrind
          ./tools/build.sh -t
          cd build
          make
      - name: Run generator tests set under valgrind
        run: |
          ./tools/valgrind-check.sh