name: Testing piplene
on: [ push ]
defaults:
  run:
    shell: bash
jobs:
  Consistent:
    name: Run library tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build tests
        run: |
          ./scripts/build.sh -t
          cd build
          make
      - name: Run matrix tests set
        run: |
          cd build
          ./build/FSEntryFinderTests
          ./build/TranslatorTests
          ./build/GeneratorTests
